# Generated by Django 5.0.14 on 2025-07-08 14:34

import uuid

import django.db.models.deletion
import pipeline.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchingPipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of the matching pipeline",
                        max_length=200,
                    ),
                ),
                (
                    "match_columns",
                    models.JSONField(
                        default=list,
                        help_text="List of column names to match on, e.g., ['col0', 'col1', 'col2']",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending - Waiting for parties to upload data"),
                            ("READY", "Ready - All parties uploaded, waiting to start"),
                            ("RUNNING", "Running - Pipeline is executing"),
                            ("COMPLETED", "Completed - Pipeline finished successfully"),
                            ("FAILED", "Failed - Pipeline execution failed"),
                            ("CANCELLED", "Cancelled - Pipeline was cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "parties_accepted",
                    models.IntegerField(
                        default=0, help_text="Number of parties that have accepted"
                    ),
                ),
                (
                    "execution_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When pipeline execution started",
                        null=True,
                    ),
                ),
                (
                    "execution_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When pipeline execution completed",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if pipeline failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_pipelines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching Pipeline",
                "verbose_name_plural": "Matching Pipelines",
            },
        ),
        migrations.CreateModel(
            name="PipelineParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Data file uploaded by this party",
                        null=True,
                        upload_to=pipeline.models.upload_to_pipeline_files,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this party has accepted the pipeline",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="pipeline.matchingpipeline",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_parties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Party",
                "verbose_name_plural": "Pipeline Parties",
                "unique_together": {("pipeline", "user")},
            },
        ),
    ]
