# Generated by Django 5.0.14 on 2025-07-11 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_matchingpipeline_celery_task_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="matchingpipeline",
            name="output_struct",
            field=models.CharField(
                blank=True,
                help_text="Directory path containing the Parquet files",
                max_length=500,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MatchedData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "right_partes",
                    models.JSONField(
                        default=list,
                        help_text="List of user IDs for the left parties in the match",
                    ),
                ),
                (
                    "folder_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the folder containing matched data",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending - Waiting for parties to upload data"),
                            ("READY", "Ready - All parties uploaded, waiting to start"),
                            ("RUNNING", "Running - Pipeline is executing"),
                            ("COMPLETED", "Completed - Pipeline finished successfully"),
                            ("FAILED", "Failed - Pipeline execution failed"),
                            ("CANCELLED", "Cancelled - Pipeline was cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "left_party",
                    models.ForeignKey(
                        help_text="User ID of the right party in the match",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_party_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_data",
                        to="pipeline.matchingpipeline",
                    ),
                ),
            ],
        ),
    ]
