# Generated by Django 5.0.14 on 2025-07-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_matchingpipeline_output_struct_matcheddata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matcheddata",
            old_name="right_partes",
            new_name="right_parties",
        ),
    ]
