# Generated by Django 5.0.14 on 2025-07-11 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0005_alter_matcheddata_left_party_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matcheddata",
            name="right_parties",
        ),
        migrations.AddField(
            model_name="matcheddata",
            name="right_parties",
            field=models.ManyToManyField(
                help_text="Users on the right party in the match",
                related_name="right_party_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
