# Generated by Django 5.0.14 on 2025-07-11 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_rename_right_partes_matcheddata_right_parties"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="matcheddata",
            name="left_party",
            field=models.ForeignKey(
                help_text="User ID of the right party in the match",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="left_party_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="matcheddata",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matched_data",
                to="pipeline.matchingpipeline",
            ),
        ),
    ]
