name: Quallity Assurance
on: [pull_request, workflow_call]

jobs:
  qa:
    name: qa
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: joinserver
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data
        ports:
          - "5432:5432"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            persist-credentials: false

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make gcc libpq-dev curl python3-distutils
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 2.1.3

      - name: Install Dependencies
        run: make install

      - name: Lint
        run: make lint
